-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Tiny.

module Tiny.PrintTiny where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Tiny.AbsTiny

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Tiny.AbsTiny.Ident where
  prt _ (Tiny.AbsTiny.Ident i) = doc $ showString i
instance Print Tiny.AbsTiny.Program where
  prt i = \case
    Tiny.AbsTiny.Prog stmt -> prPrec i 0 (concatD [prt 0 stmt])

instance Print Tiny.AbsTiny.Decl where
  prt i = \case
    Tiny.AbsTiny.DVar id_ exp -> prPrec i 0 (concatD [doc (showString "var"), prt 0 id_, doc (showString "="), prt 0 exp])

instance Print [Tiny.AbsTiny.Decl] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Tiny.AbsTiny.Stmt where
  prt i = \case
    Tiny.AbsTiny.SSkip -> prPrec i 0 (concatD [doc (showString "skip")])
    Tiny.AbsTiny.SVar id_ exp -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":="), prt 0 exp])
    Tiny.AbsTiny.SSem stmt1 stmt2 -> prPrec i 0 (concatD [prt 0 stmt1, doc (showString ";"), prt 0 stmt2])
    Tiny.AbsTiny.SIfElse bexp stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 bexp, doc (showString "then"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2, doc (showString "fi")])
    Tiny.AbsTiny.SWhile bexp stmt -> prPrec i 0 (concatD [doc (showString "while"), prt 0 bexp, doc (showString "do"), prt 0 stmt, doc (showString "end")])
    Tiny.AbsTiny.SBlock decls stmt -> prPrec i 0 (concatD [doc (showString "begin"), prt 0 decls, prt 0 stmt, doc (showString "end")])

instance Print Tiny.AbsTiny.Exp where
  prt i = \case
    Tiny.AbsTiny.EAdd exp1 addop exp2 -> prPrec i 0 (concatD [prt 0 exp1, prt 0 addop, prt 1 exp2])
    Tiny.AbsTiny.EMul exp1 mulop exp2 -> prPrec i 1 (concatD [prt 1 exp1, prt 0 mulop, prt 2 exp2])
    Tiny.AbsTiny.ENeg exp -> prPrec i 2 (concatD [doc (showString "-"), prt 3 exp])
    Tiny.AbsTiny.EInt n -> prPrec i 3 (concatD [prt 0 n])
    Tiny.AbsTiny.EVar id_ -> prPrec i 3 (concatD [prt 0 id_])

instance Print Tiny.AbsTiny.BExp where
  prt i = \case
    Tiny.AbsTiny.BOr bexp1 bexp2 -> prPrec i 0 (concatD [prt 1 bexp1, doc (showString "or"), prt 0 bexp2])
    Tiny.AbsTiny.BAnd bexp1 bexp2 -> prPrec i 1 (concatD [prt 2 bexp1, doc (showString "and"), prt 1 bexp2])
    Tiny.AbsTiny.BRel exp1 relop exp2 -> prPrec i 2 (concatD [prt 0 exp1, prt 0 relop, prt 0 exp2])
    Tiny.AbsTiny.BNeg bexp -> prPrec i 2 (concatD [doc (showString "not"), prt 3 bexp])
    Tiny.AbsTiny.BT -> prPrec i 3 (concatD [doc (showString "true")])
    Tiny.AbsTiny.BF -> prPrec i 3 (concatD [doc (showString "false")])

instance Print Tiny.AbsTiny.AddOp where
  prt i = \case
    Tiny.AbsTiny.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    Tiny.AbsTiny.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print Tiny.AbsTiny.MulOp where
  prt i = \case
    Tiny.AbsTiny.Times -> prPrec i 0 (concatD [doc (showString "*")])
    Tiny.AbsTiny.Div -> prPrec i 0 (concatD [doc (showString "/")])
    Tiny.AbsTiny.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print Tiny.AbsTiny.RelOp where
  prt i = \case
    Tiny.AbsTiny.LT -> prPrec i 0 (concatD [doc (showString "<")])
    Tiny.AbsTiny.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    Tiny.AbsTiny.GT -> prPrec i 0 (concatD [doc (showString ">")])
    Tiny.AbsTiny.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    Tiny.AbsTiny.EQ -> prPrec i 0 (concatD [doc (showString "==")])
    Tiny.AbsTiny.NE -> prPrec i 0 (concatD [doc (showString "!=")])
